# Generated by Django 5.0.6 on 2024-06-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
