# Generated by Django 5.0.6 on 2024-06-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calebform', '0002_formdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='FormModel',
        ),
    ]
