# Generated by Django 5.0.6 on 2024-06-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calebform', '0003_rename_formdata_formmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormModel',
            new_name='CalebFormModel',
        ),
    ]
