# Generated by Django 5.0.6 on 2024-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.CharField(max_length=120),
        ),
    ]
