# Generated by Django 5.0.6 on 2024-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_age_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Untitled', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
